version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    env_file:
      - ".env"
    volumes:
      - ./frontend/src:/frontend/src

    restart: unless-stopped